<a href="https://colab.research.google.com/github/olihile84-tech/exercise-syntax-variables-and-numbers/blob/main/NUmPy_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a
a.shape
a.ndim
a.dtype.name
a.itemsize
a.size
type(a)
b = np.array([6, 7, 8])
b
type(b)
b = np.array([6, 7, 8])
print("b =", b)
print("type:", type(b))

b = [6 7 8]
type: <class 'numpy.ndarray'>


In [ ]:
a = np.array([1, 2, 3, 4])

print("array:", a)
print("shape:", a.shape)
print("ndim:", a.ndim)
print("dtype:", a.dtype)
print("size:", a.size)

array: [1 2 3 4]
shape: (4,)
ndim: 1
dtype: int64
size: 4


In [ ]:

a = np.array([1, 2, 3, 4])

In [ ]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])


print("shape:", b.shape)
print("ndim:", b.ndim)
print("dtype:", b.dtype)

shape: (2, 3)
ndim: 2
dtype: float64


In [ ]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
print("shape:", c.shape)
print("ndim:", c.ndim)
print("dtype:", c.dtype)
print(c)

shape: (2, 2)
ndim: 2
dtype: complex128
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [ ]:
import numpy as np

prices = np.array([1.1000, 1.1050, 1.0950, 1.1100])
print("shape:", prices.shape)
print("ndim:", prices.ndim)
print(prices)

shape: (4,)
ndim: 1
[1.1   1.105 1.095 1.11 ]


In [ ]:
ohlcv = np.array([
    [1.1000, 1.1100, 1.0950, 1.1050, 1000],  # Day 1
    [1.1050, 1.1200, 1.1000, 1.1150, 1500],  # Day 2
    [1.1150, 1.1300, 1.1100, 1.1250, 2000],  # Day 3
    [1.1250, 1.1400, 1.1200, 1.1350, 1800],  # Day 4
])
print("shape:", ohlcv.shape)
print("ndim:", ohlcv.ndim)
print(ohlcv)

shape: (4, 5)
ndim: 2
[[1.100e+00 1.110e+00 1.095e+00 1.105e+00 1.000e+03]
 [1.105e+00 1.120e+00 1.100e+00 1.115e+00 1.500e+03]
 [1.115e+00 1.130e+00 1.110e+00 1.125e+00 2.000e+03]
 [1.125e+00 1.140e+00 1.120e+00 1.135e+00 1.800e+03]]


In [ ]:
import numpy as np

price_float64 = np.array([1.10001234567890], dtype=np.float64)
print("float64:",price_float64)

price_float32 = np.array([1.10001234567890], dtype=np.float32)
print("float32:", price_float32)

volume_int64 = np.array([1000000000], dtype=np.int64)
print("int64:", volume_int64)

volume_int32 = np.array([1000000000], dtype=np.int32)
print("int32:",volume_int32)

trades_int16 = np.array([100], dtype=np.int16)
print("int16:", trades_int16)

float64: [1.10001235]
float32: [1.1000123]
int64: [1000000000]
int32: [1000000000]
int16: [100]


In [ ]:
""

''

In [ ]:
import numpy as np

trade_prices = np.zeros((5,4))
print("Black OHLC table(5 candles):")
print(trade_prices)
print()

risk_multipliers = np.ones((3, 4), dtype=np.int16)
print("Risk multipliers:")
print(risk_multipliers)
print()

two_weekes_ohlc = np.ones((2, 5, 4))
print("2 weeks of OHLC (2 weeks, 5 days, 4 values):")
print(two_weekes_ohlc)
print()

price_storage = np.empty((3, 4))
print("Empty price storage(random memory):")
print(price_storage)

Black OHLC table(5 candles):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Risk multipliers:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

2 weeks of OHLC (2 weeks, 5 days, 4 values):
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

Empty price storage(random memory):
[[4.89840055e-315 0.00000000e+000 2.10077583e-312 6.79038654e-313]
 [2.22809558e-312 2.14321575e-312 2.35541533e-312 6.79038654e-313]
 [2.22809558e-312 2.14321575e-312 2.46151512e-312 2.41907520e-312]]


In [ ]:
from numpy import pi
np.linspace(0, 2, 9)                   # 9 numbers from 0 to 2
x = np.linspace(0, 2 * pi, 100)        # useful to evaluate function at lots of points
f = np.sin(x)

print(np.linspace(0,2,9))
print("f shape:", x.shape)
print("f shape", f.shape)
print("first 5 sin values:", f[:5])

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
f shape: (100,)
f shape (100,)
first 5 sin values: [0.         0.06342392 0.12659245 0.18925124 0.25114799]


In [ ]:
import numpy as np
from numpy import pi

print("arange whole numbers:")
print(np.arange(10, 30, 5))
print()

print("arange with floats:")
print(np.arange(0, 2, 0.3))
print("count:", len(np.arange(0, 2, 0.3)))
print()

print("linspace 9 nummbers:")
print(np.linspace(0, 2, 9))
print("count:", len(np.linspace(0, 2, 9)))
print()

support = 1.1000
resistance = 1.1500
levels = np.linspace(support, resistance, 10)
print("Trading price levels:")
print(levels)

arange whole numbers:
[10 15 20 25]

arange with floats:
[0.  0.3 0.6 0.9 1.2 1.5 1.8]
count: 7

linspace 9 nummbers:
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
count: 9

Trading price levels:
[1.1        1.10555556 1.11111111 1.11666667 1.12222222 1.12777778
 1.13333333 1.13888889 1.14444444 1.15      ]


In [ ]:
import numpy as np

prices = np.array([1.10, 1.11, 1.09])

blank = np.zeros_like(prices)
print("zeros_like:", blank)

random_moves =  np.random.random(5)
print("random moves:", random_moves)

zeros_like: [0. 0. 0.]
random moves: [0.5046094  0.51368453 0.16673962 0.79484913 0.36264098]


In [ ]:
import numpy as np

a = np.arange(6)
print(a)

b = np.arange(12).reshape(4, 3)
print(b)

c = np.arange(24).reshape(2, 3, 4)
print(c)

[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
import numpy as np
np.set_printoptions(threshold=np.inf)
print(np.arange(100))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
import numpy as np
import sys

np.set_printoptions(threshold=sys.maxsize)
print(np.arange(100))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
np.set_printoptions(threshold=1000)
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [ ]:
import numpy as np

a = np.array([20, 30, 40, 50])
b = np.arange(4)

print("b:", b)
print("c = a-b:", a-b)
print("b squared:", b**2)
print("10 * sin(a):", 10 * np.sin(a))
print("a < 35:", a < 35)

b: [0 1 2 3]
c = a-b: [20 29 38 47]
b squared: [0 1 4 9]
10 * sin(a): [ 9.12945251 -9.88031624  7.4511316  -2.62374854]
a < 35: [ True  True False False]


In [ ]:
import numpy as np

A = np.array([[1,1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])

print("Elementwise * :")
print(A * B)

print("\nMatrix product @:")
print(A @ B)

print("\nMatrix product .dot():")
print(A.dot(B))

Elementwise * :
[[2 0]
 [0 4]]

Matrix product @:
[[5 4]
 [3 4]]

Matrix product .dot():
[[5 4]
 [3 4]]


In [ ]:
import numpy as np

rg = np.random.default_rng(1)
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))

print("a before:", a)
a *= 3
print("a after *=3:", a)
b += a
print("b after +=a:", b)



a before: [[1 1 1]
 [1 1 1]]
a after *=3: [[3 3 3]
 [3 3 3]]
b after +=a: [[3.51182162 3.9504637  3.14415961]
 [3.94864945 3.31183145 3.42332645]]


In [ ]:
import numpy as np

rg = np.random.default_rng(1)
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))

print("a before:", a)
a *= 3
print("a after *=3:", a)
b += a
print("b after +=a:", b)

a += b
print("a after +=:", a)

a before: [[1 1 1]
 [1 1 1]]
a after *=3: [[3 3 3]
 [3 3 3]]
b after +=a: [[3.51182162 3.9504637  3.14415961]
 [3.94864945 3.31183145 3.42332645]]


UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [ ]:
import numpy as np
from numpy import pi

a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)

print("a dtype:", a.dtype)
print("b dtype:", b.dtype)

c = a + b
print("c dtype:", c.dtype)
print("c:", c)

a dtype: int32
b dtype: float64
c dtype: float64
c: [1.         2.57079633 4.14159265]


In [ ]:
import numpy as np

volume = np.array([1000, 2000, 3000], dtype=np.int32)
price = np.array([1.1050, 1.1100, 1.1075], dtype=np.float64)

trade_value = volume * price
print("trade values:", trade_value)

trade values: [1105.  2220.  3322.5]


In [ ]:
import numpy as np

pnl = np.array([150.0, -50.0, 200.0, -25.0, 300.0, -100.0])

print("ALL PnL:", pnl)
print()
print("Total Profit:", pnl.sum())
print("Worst Trade:", pnl.min())
print("Best Trade:", pnl.max())
print("Average Trade:", pnl.mean())

ALL PnL: [ 150.  -50.  200.  -25.  300. -100.]

Total Profit: 475.0
Worst Trade: -100.0
Best Trade: 300.0
Average Trade: 79.16666666666667


In [ ]:
import numpy as np

pnl_table = np.array([
    [150.0, -50.0, 200.0],
     [-25.0, 300.0, -100.0]
])

print("Sum per session (axis=1):")
print(pnl_table.sum(axis=1))


print("\nBest trade per round (axis=0):")
print(pnl_table.sum(axis=0))

print("\nWorst trade per round (axis=0):")
print(pnl_table.min(axis=0))

Sum per session (axis=1):
[300. 175.]

Best trade per round (axis=0):
[125. 250. 100.]

Worst trade per round (axis=0):
[ -25.  -50. -100.]


In [ ]:
import numpy as np

daily_pnl = np.array([150, -50, 200, -25, 300, -100])
equity_curve = np.cumsum(daily_pnl)

print("Daily PnL:", daily_pnl)
print("Equity curve:", equity_curve)

Daily PnL: [ 150  -50  200  -25  300 -100]
Equity curve: [150 100 300 275 575 475]


In [ ]:
import numpy as np

rg = np.random.default_rng(1)
a = rg.random((2, 3))

print("array:")
print(a)
print()
print("sum:", a.sum())
print("min:", a.min())
print("max:", a.max())

array:
[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]

sum: 3.290252281866131
min: 0.14415961271963373
max: 0.9504636963259353


In [ ]:
moves = rg.random((2, 3))
print("Biggest move:", moves.max())
print("Smallest move:", moves.min())
print("Total movement:", moves.sum())

Biggest move: 0.8277025938204418
Smallest move: 0.027559113243068367
Total movement: 3.1057109529998157
