<a href="https://colab.research.google.com/github/olihile84-tech/exercise-syntax-variables-and-numbers/blob/main/NUmPy_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

trades = {
    'pair': ['EURUSD', 'GBPJPY', 'EURUSD', 'XAUUSD', 'GBPJPY'],
    'session': ['London', 'Tokyo', 'New York', 'London', 'New York'],
    'entry': [1.1000, 185.00, 1.0950, 1920.00, 184.20],
    'exit': [1.1050, 184.50, 1.0900, 1935.00, 184.20],
    'sl': [1.0980, 185.20, 1.0970, 1915.00, 184.20],
    'result': ['win', 'loss', 'loss', 'win', 'win']
}
journal = pd.DataFrame(trades)

ACCOUNT_BALANCE = 10000
RISK_PERCENT = 0.25

# ─── DEFINE FUNCTIONS ───
def calculate_rr(row):
    risk = abs(row['entry'] - row['sl'])
    reward = abs(row['exit'] - row['entry'])
    return 0 if risk == 0 else round(reward / risk, 2)

def calculate_pnl(row):
    cash_at_risk = ACCOUNT_BALANCE * (RISK_PERCENT / 100)
    if row['result'] == 'win':
        return round(cash_at_risk * row['rr'], 2)
    else:
        return round(-cash_at_risk, 2)

# ─── CALL FUNCTIONS (UNINDENTED = OUTSIDE FUNCTIONS) ───
journal['rr'] = journal.apply(calculate_rr, axis=1)
journal['pnl'] = journal.apply(calculate_pnl, axis=1)

# ─── NUMPY PIPS ───
diff = journal['exit'] - journal['entry']
is_jpy = journal['pair'].str.contains('JPY')
is_xau = journal['pair'].str.contains('XAU')

journal['pips'] = np.select(
    [is_jpy, is_xau],
    [diff * 100, diff * 10],
    default=diff * 10000
)

# ─── CUMULATIVE ───
journal['cumulative_pnl'] = np.cumsum(journal['pnl'])

# ─── PRINT ───
print(journal[['pair', 'entry', 'exit', 'rr', 'pips', 'pnl', 'cumulative_pnl']])

     pair     entry      exit   rr   pips   pnl  cumulative_pnl
0  EURUSD     1.100     1.105  2.5   50.0  62.5            62.5
1  GBPJPY   185.000   184.500  2.5  -50.0 -25.0            37.5
2  EURUSD     1.095     1.090  2.5  -50.0 -25.0            12.5
3  XAUUSD  1920.000  1935.000  3.0  150.0  75.0            87.5
4  GBPJPY   184.200   184.200  0.0    0.0   0.0            87.5


In [2]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a
a.shape
a.ndim
a.dtype.name
a.itemsize
a.size
type(a)
b = np.array([6, 7, 8])
b
type(b)
b = np.array([6, 7, 8])
print("b =", b)
print("type:", type(b))

b = [6 7 8]
type: <class 'numpy.ndarray'>


In [3]:
a = np.array([1, 2, 3, 4])

print("array:", a)
print("shape:", a.shape)
print("ndim:", a.ndim)
print("dtype:", a.dtype)
print("size:", a.size)

array: [1 2 3 4]
shape: (4,)
ndim: 1
dtype: int64
size: 4


In [4]:

a = np.array([1, 2, 3, 4])

In [5]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])


print("shape:", b.shape)
print("ndim:", b.ndim)
print("dtype:", b.dtype)

shape: (2, 3)
ndim: 2
dtype: float64


In [6]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
print("shape:", c.shape)
print("ndim:", c.ndim)
print("dtype:", c.dtype)
print(c)

shape: (2, 2)
ndim: 2
dtype: complex128
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [7]:
import numpy as np

prices = np.array([1.1000, 1.1050, 1.0950, 1.1100])
print("shape:", prices.shape)
print("ndim:", prices.ndim)
print(prices)

shape: (4,)
ndim: 1
[1.1   1.105 1.095 1.11 ]


In [8]:
ohlcv = np.array([
    [1.1000, 1.1100, 1.0950, 1.1050, 1000],  # Day 1
    [1.1050, 1.1200, 1.1000, 1.1150, 1500],  # Day 2
    [1.1150, 1.1300, 1.1100, 1.1250, 2000],  # Day 3
    [1.1250, 1.1400, 1.1200, 1.1350, 1800],  # Day 4
])
print("shape:", ohlcv.shape)
print("ndim:", ohlcv.ndim)
print(ohlcv)

shape: (4, 5)
ndim: 2
[[1.100e+00 1.110e+00 1.095e+00 1.105e+00 1.000e+03]
 [1.105e+00 1.120e+00 1.100e+00 1.115e+00 1.500e+03]
 [1.115e+00 1.130e+00 1.110e+00 1.125e+00 2.000e+03]
 [1.125e+00 1.140e+00 1.120e+00 1.135e+00 1.800e+03]]


In [9]:
import numpy as np

price_float64 = np.array([1.10001234567890], dtype=np.float64)
print("float64:",price_float64)

price_float32 = np.array([1.10001234567890], dtype=np.float32)
print("float32:", price_float32)

volume_int64 = np.array([1000000000], dtype=np.int64)
print("int64:", volume_int64)

volume_int32 = np.array([1000000000], dtype=np.int32)
print("int32:",volume_int32)

trades_int16 = np.array([100], dtype=np.int16)
print("int16:", trades_int16)

float64: [1.10001235]
float32: [1.1000123]
int64: [1000000000]
int32: [1000000000]
int16: [100]


In [10]:
""

''

In [11]:
import numpy as np

trade_prices = np.zeros((5,4))
print("Black OHLC table(5 candles):")
print(trade_prices)
print()

risk_multipliers = np.ones((3, 4), dtype=np.int16)
print("Risk multipliers:")
print(risk_multipliers)
print()

two_weekes_ohlc = np.ones((2, 5, 4))
print("2 weeks of OHLC (2 weeks, 5 days, 4 values):")
print(two_weekes_ohlc)
print()

price_storage = np.empty((3, 4))
print("Empty price storage(random memory):")
print(price_storage)

Black OHLC table(5 candles):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Risk multipliers:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

2 weeks of OHLC (2 weeks, 5 days, 4 values):
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

Empty price storage(random memory):
[[2.55199749e-315 0.00000000e+000 2.10077583e-312 6.79038654e-313]
 [2.22809558e-312 2.14321575e-312 2.35541533e-312 6.79038654e-313]
 [2.22809558e-312 2.14321575e-312 2.46151512e-312 2.41907520e-312]]


In [12]:
from numpy import pi
np.linspace(0, 2, 9)                   # 9 numbers from 0 to 2
x = np.linspace(0, 2 * pi, 100)        # useful to evaluate function at lots of points
f = np.sin(x)

print(np.linspace(0,2,9))
print("f shape:", x.shape)
print("f shape", f.shape)
print("first 5 sin values:", f[:5])

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
f shape: (100,)
f shape (100,)
first 5 sin values: [0.         0.06342392 0.12659245 0.18925124 0.25114799]


In [13]:
import numpy as np
from numpy import pi

print("arange whole numbers:")
print(np.arange(10, 30, 5))
print()

print("arange with floats:")
print(np.arange(0, 2, 0.3))
print("count:", len(np.arange(0, 2, 0.3)))
print()

print("linspace 9 nummbers:")
print(np.linspace(0, 2, 9))
print("count:", len(np.linspace(0, 2, 9)))
print()

support = 1.1000
resistance = 1.1500
levels = np.linspace(support, resistance, 10)
print("Trading price levels:")
print(levels)

arange whole numbers:
[10 15 20 25]

arange with floats:
[0.  0.3 0.6 0.9 1.2 1.5 1.8]
count: 7

linspace 9 nummbers:
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
count: 9

Trading price levels:
[1.1        1.10555556 1.11111111 1.11666667 1.12222222 1.12777778
 1.13333333 1.13888889 1.14444444 1.15      ]


In [14]:
import numpy as np

prices = np.array([1.10, 1.11, 1.09])

blank = np.zeros_like(prices)
print("zeros_like:", blank)

random_moves =  np.random.random(5)
print("random moves:", random_moves)

zeros_like: [0. 0. 0.]
random moves: [0.33079162 0.74905176 0.19538001 0.0287619  0.11846195]


In [15]:
import numpy as np

a = np.arange(6)
print(a)

b = np.arange(12).reshape(4, 3)
print(b)

c = np.arange(24).reshape(2, 3, 4)
print(c)

[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [16]:
import numpy as np
np.set_printoptions(threshold=np.inf)
print(np.arange(100))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [17]:
import numpy as np
import sys

np.set_printoptions(threshold=sys.maxsize)
print(np.arange(100))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [18]:
np.set_printoptions(threshold=1000)
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [19]:
import numpy as np

a = np.array([20, 30, 40, 50])
b = np.arange(4)

print("b:", b)
print("c = a-b:", a-b)
print("b squared:", b**2)
print("10 * sin(a):", 10 * np.sin(a))
print("a < 35:", a < 35)

b: [0 1 2 3]
c = a-b: [20 29 38 47]
b squared: [0 1 4 9]
10 * sin(a): [ 9.12945251 -9.88031624  7.4511316  -2.62374854]
a < 35: [ True  True False False]


In [20]:
import numpy as np

A = np.array([[1,1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])

print("Elementwise * :")
print(A * B)

print("\nMatrix product @:")
print(A @ B)

print("\nMatrix product .dot():")
print(A.dot(B))

Elementwise * :
[[2 0]
 [0 4]]

Matrix product @:
[[5 4]
 [3 4]]

Matrix product .dot():
[[5 4]
 [3 4]]


In [21]:
import numpy as np

rg = np.random.default_rng(1)
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))

print("a before:", a)
a *= 3
print("a after *=3:", a)
b += a
print("b after +=a:", b)



a before: [[1 1 1]
 [1 1 1]]
a after *=3: [[3 3 3]
 [3 3 3]]
b after +=a: [[3.51182162 3.9504637  3.14415961]
 [3.94864945 3.31183145 3.42332645]]


In [22]:
import numpy as np

rg = np.random.default_rng(1)
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))

print("a before:", a)
a *= 3
print("a after *=3:", a)
b += a
print("b after +=a:", b)



a before: [[1 1 1]
 [1 1 1]]
a after *=3: [[3 3 3]
 [3 3 3]]
b after +=a: [[3.51182162 3.9504637  3.14415961]
 [3.94864945 3.31183145 3.42332645]]


In [23]:
import numpy as np
from numpy import pi

a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)

print("a dtype:", a.dtype)
print("b dtype:", b.dtype)

c = a + b
print("c dtype:", c.dtype)
print("c:", c)

a dtype: int32
b dtype: float64
c dtype: float64
c: [1.         2.57079633 4.14159265]


In [24]:
import numpy as np

volume = np.array([1000, 2000, 3000], dtype=np.int32)
price = np.array([1.1050, 1.1100, 1.1075], dtype=np.float64)

trade_value = volume * price
print("trade values:", trade_value)

trade values: [1105.  2220.  3322.5]


In [25]:
import numpy as np

pnl = np.array([150.0, -50.0, 200.0, -25.0, 300.0, -100.0])

print("ALL PnL:", pnl)
print()
print("Total Profit:", pnl.sum())
print("Worst Trade:", pnl.min())
print("Best Trade:", pnl.max())
print("Average Trade:", pnl.mean())

ALL PnL: [ 150.  -50.  200.  -25.  300. -100.]

Total Profit: 475.0
Worst Trade: -100.0
Best Trade: 300.0
Average Trade: 79.16666666666667


In [26]:
import numpy as np

pnl_table = np.array([
    [150.0, -50.0, 200.0],
     [-25.0, 300.0, -100.0]
])

print("Sum per session (axis=1):")
print(pnl_table.sum(axis=1))


print("\nBest trade per round (axis=0):")
print(pnl_table.sum(axis=0))

print("\nWorst trade per round (axis=0):")
print(pnl_table.min(axis=0))

Sum per session (axis=1):
[300. 175.]

Best trade per round (axis=0):
[125. 250. 100.]

Worst trade per round (axis=0):
[ -25.  -50. -100.]


In [27]:
import numpy as np

daily_pnl = np.array([150, -50, 200, -25, 300, -100])
equity_curve = np.cumsum(daily_pnl)

print("Daily PnL:", daily_pnl)
print("Equity curve:", equity_curve)

Daily PnL: [ 150  -50  200  -25  300 -100]
Equity curve: [150 100 300 275 575 475]


In [28]:
import numpy as np

rg = np.random.default_rng(1)
a = rg.random((2, 3))

print("array:")
print(a)
print()
print("sum:", a.sum())
print("min:", a.min())
print("max:", a.max())

array:
[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]

sum: 3.290252281866131
min: 0.14415961271963373
max: 0.9504636963259353


In [29]:
moves = rg.random((2, 3))
print("Biggest move:", moves.max())
print("Smallest move:", moves.min())
print("Total movement:", moves.sum())

Biggest move: 0.8277025938204418
Smallest move: 0.027559113243068367
Total movement: 3.1057109529998157


In [30]:
import pandas as pd
import numpy as np

journal['pips'] = np.where(
     journal['pair'].str.contains('JPY'),
    (journal['exit'] - journal['entry'])* 100,
    np.where(
        journal['pair'].str.contains('XAU'),
        (journal['exit'] - journal['entry']) * 10,
        (journal['exit'] - journal['entry']) * 10000
        )
)

journal['pnl'] = journal.apply(calculate_pnl, axis=1)

journal['cumulative_pnl'] = \
np.cumsum(journal['pnl'])

print(journal[['pair','pnl', 'cumulative_pnl']])

     pair   pnl  cumulative_pnl
0  EURUSD  62.5            62.5
1  GBPJPY -25.0            37.5
2  EURUSD -25.0            12.5
3  XAUUSD  75.0            87.5
4  GBPJPY   0.0            87.5


In [31]:
import numpy as np

ohlc = np.array([
    [1.1000, 1.1100, 1.0950, 1.1050],
    [1.1050, 1.1200, 1.1000, 1.1150],
    [1.1150, 1.1300, 1.1100, 1.1250],
    [1.1250, 1.1400, 1.1200, 1.3500],
    [1.1350, 1.1500, 1.1300, 1.1450],
])

print("Day 2 Close:", ohlc[2,3])
print("All Highs:", ohlc[0:5, 1])
print("All Highs:", ohlc[:, 1])
print("Days 1-2 full data:\n", ohlc[1:3, :])

Day 2 Close: 1.125
All Highs: [1.11 1.12 1.13 1.14 1.15]
All Highs: [1.11 1.12 1.13 1.14 1.15]
Days 1-2 full data:
 [[1.105 1.12  1.1   1.115]
 [1.115 1.13  1.11  1.125]]


In [32]:
trades = np.array([
    [62.50, 1.25, 25.0],
    [-25.00, 0.25, 25.0],
    [-25.00, 15.5, 50.0],
    [75.00, 0.05, 25.0],
    [58.33, 1.25, 25.0],
])

print("All P&L:", trades[:, 0])
print("Lots trades 2-4:", trades[2:5, 1])
print("Winning trades:\n", trades[[0, 3, 4], :])

All P&L: [ 62.5  -25.   -25.    75.    58.33]
Lots trades 2-4: [15.5   0.05  1.25]
Winning trades:
 [[6.250e+01 1.250e+00 2.500e+01]
 [7.500e+01 5.000e-02 2.500e+01]
 [5.833e+01 1.250e+00 2.500e+01]]


In [33]:
import numpy as np

diff = journal['exit'] - journal['entry']

is_jpy = journal['pair'].str.contains('JPY')
is_xau = journal['pair'].str.contains('XAU')

journal['pips'] = np.select(
    [is_jpy, is_xau],
    [diff * 100, diff * 10],
    default=diff * 10000
)

print(journal[['pair', 'exit', 'entry', 'pips']])

     pair      exit     entry   pips
0  EURUSD     1.105     1.100   50.0
1  GBPJPY   184.500   185.000  -50.0
2  EURUSD     1.090     1.095  -50.0
3  XAUUSD  1935.000  1920.000  150.0
4  GBPJPY   184.200   184.200    0.0


In [34]:
ohlcv = np.ones((2, 5, 4))

closes = ohlcv[..., 3]
print("Closes:\n", closes)


Closes:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [35]:
 b = np.array([
     [0, 1, 2, 3],
     [10, 11, 12, 13],
     [20, 21, 22, 23],

 ])

for element in b.flat:
  print(element)


0
1
2
3
10
11
12
13
20
21
22
23


In [36]:
ohlc = np.array([
    [1.1000, 1.1100, 1.0950, 1.1050],
    [1.1050, 1.1200, 1.1000, 1.1150],
])

threshold = 1.11

for price in ohlc.flat:
  if price > threshold:
    print(f"Price{price:.4f}broke above threshold {threshold}")

Price1.1200broke above threshold 1.11
Price1.1150broke above threshold 1.11


In [37]:
for i, price in enumerate(ohlc.flat):
  row = i // 4
  col = i % 4


  labels = ['Open', 'High', 'Low', 'Close']

  if price > 1.11:
    print (f"Day {row+1} {labels[col]}:{price:.4f} > 1.11")

Day 2 High:1.1200 > 1.11
Day 2 Close:1.1150 > 1.11


In [38]:
mask = ohlc > 1.11
above_threshold = ohlc[mask]

print("Prices above 1.11:", above_threshold)


Prices above 1.11: [1.12  1.115]


In [39]:
import numpy as np

rg = np.random.default_rng(1)
a = np.floor(10 * rg.random((3, 4)))
print(a)
print("shape:", a.shape)

[[5. 9. 1. 9.]
 [3. 4. 8. 4.]
 [5. 0. 7. 5.]]
shape: (3, 4)


In [40]:
import numpy as np

a = np.array([[3., 7., 3., 4.],
              [1., 4., 2., 2.],
              [7., 2., 4., 9.]])

print(a)

a.resize((2, 6))

print(a)

[[3. 7. 3. 4.]
 [1. 4. 2. 2.]
 [7. 2. 4. 9.]]
[[3. 7. 3. 4. 1. 4.]
 [2. 2. 7. 2. 4. 9.]]


In [41]:
import numpy as np


a = np.array([
    [1.1000, 1.1100, 1.0950, 1.1050],
    [1.1050, 1.1200, 1.1000, 1.1150],
    [1.1150, 1.1300, 1.1100, 1.1250],
])

print("Original OHLC (3 days, 4 values):")
print(a)
print("Shape:", a.shape)


a.resize((2, 6))

print("\nResized to (2, 6) — meaning is lost:")
print(a)
print("Shape:", a.shape)

Original OHLC (3 days, 4 values):
[[1.1   1.11  1.095 1.105]
 [1.105 1.12  1.1   1.115]
 [1.115 1.13  1.11  1.125]]
Shape: (3, 4)

Resized to (2, 6) — meaning is lost:
[[1.1   1.11  1.095 1.105 1.105 1.12 ]
 [1.1   1.115 1.115 1.13  1.11  1.125]]
Shape: (2, 6)


In [42]:
import numpy as np

a = np.array([
    [1.1000, 1.1100, 1.0950, 1.1050],
    [1.1050, 1.1200, 1.1000, 1.1150],
    [1.1150, 1.1300, 1.1100, 1.1250],
])

safe = a.reshape((2, 6))
print("Original:", a.shape)
print("New:", safe.shape)

copy = a.copy()
copy.resize((2, 6))
print("Original:", a.shape)
print("Copy:", copy.shape)

flat = a.ravel()
print("Original:", a.shape)
print("Flat:", flat.shape)

Original: (3, 4)
New: (2, 6)
Original: (3, 4)
Copy: (2, 6)
Original: (3, 4)
Flat: (12,)


In [43]:
import numpy as np

ohlc = np.array([
    [1.1000, 1.1100, 1.0950, 1.1050],
    [1.1050, 1.1200, 1.1000, 1.1150],
    [1.1150, 1.1300, 1.1100, 1.1250],
])


opens = ohlc[:, 0]
highs = ohlc[:, 1]
lows = ohlc[:, 2]
closes = ohlc[:, 3]

print("Opens:", opens)
print("Highs:", highs)
print("Lows:", lows)
print("Closes:", closes)

Opens: [1.1   1.105 1.115]
Highs: [1.11 1.12 1.13]
Lows: [1.095 1.1   1.11 ]
Closes: [1.105 1.115 1.125]


In [44]:
# 10 days of OHLC
ohlc_10 = np.array([
    [1.1000, 1.1100, 1.0950, 1.1050],
    [1.1050, 1.1200, 1.1000, 1.1150],
    [1.1150, 1.1300, 1.1100, 1.1250],
    [1.1250, 1.1400, 1.1200, 1.1350],
    [1.1350, 1.1500, 1.1300, 1.1450],
    [1.1450, 1.1550, 1.1400, 1.1500],
    [1.1500, 1.1600, 1.1450, 1.1550],
    [1.1550, 1.1650, 1.1500, 1.1600],
    [1.1600, 1.1700, 1.1550, 1.1650],
    [1.1650, 1.1750, 1.1600, 1.1700],
])


weekly = ohlc_10.reshape((2, 5, 4))

print("Shape:", weekly.shape)


print("\nWeek 1, Day 1:", weekly[0, 0])
print("Week 2, Day 3:", weekly[1, 2])


print("\nWeek 1 closes:", weekly[0, :, 3])

Shape: (2, 5, 4)

Week 1, Day 1: [1.1   1.11  1.095 1.105]
Week 2, Day 3: [1.155 1.165 1.15  1.16 ]

Week 1 closes: [1.105 1.115 1.125 1.135 1.145]


In [45]:
import numpy as np

# Your trading data: 12 elements (3 days × 4 OHLC values)
a = np.array([
    [1.1000, 1.1100, 1.0950, 1.1050],  # Day 1
    [1.1050, 1.1200, 1.1000, 1.1150],  # Day 2
    [1.1150, 1.1300, 1.1100, 1.1250],  # Day 3
])

print("Original:")
print(a)
print("Shape:", a.shape)
print("Total elements:", a.size)


print("\n--- a.reshape(3, -1) ---")
print(a.reshape(3, -1))
print("Shape:", a.reshape(3, -1).shape)  # (3, 4) ← 12÷3=4

print("\n--- a.reshape(2, -1) ---")
print(a.reshape(2, -1))
print("Shape:", a.reshape(2, -1).shape)  # (2, 6) ← 12÷2=6

print("\n--- a.reshape(-1, 4) ---")
print(a.reshape(-1, 4))
print("Shape:", a.reshape(-1, 4).shape)

print("\n--- a.reshape(-1) ---")
print(a.reshape(-1))
print("Shape:", a.reshape(-1).shape)

Original:
[[1.1   1.11  1.095 1.105]
 [1.105 1.12  1.1   1.115]
 [1.115 1.13  1.11  1.125]]
Shape: (3, 4)
Total elements: 12

--- a.reshape(3, -1) ---
[[1.1   1.11  1.095 1.105]
 [1.105 1.12  1.1   1.115]
 [1.115 1.13  1.11  1.125]]
Shape: (3, 4)

--- a.reshape(2, -1) ---
[[1.1   1.11  1.095 1.105 1.105 1.12 ]
 [1.1   1.115 1.115 1.13  1.11  1.125]]
Shape: (2, 6)

--- a.reshape(-1, 4) ---
[[1.1   1.11  1.095 1.105]
 [1.105 1.12  1.1   1.115]
 [1.115 1.13  1.11  1.125]]
Shape: (3, 4)

--- a.reshape(-1) ---
[1.1   1.11  1.095 1.105 1.105 1.12  1.1   1.115 1.115 1.13  1.11  1.125]
Shape: (12,)


In [46]:
import numpy as np

rg = np.random.default_rng(1)
a = np.floor(10 * rg.random((3, 4)))

print("original:\n", a)
print("shape:", a.shape)
print()
print("ravel:", a.ravel())
print()
print("reshape:\n", a.reshape(6, 2))
print()
print("transpose:\n", a.T)
print("T shape:", a.T.shape)

original:
 [[5. 9. 1. 9.]
 [3. 4. 8. 4.]
 [5. 0. 7. 5.]]
shape: (3, 4)

ravel: [5. 9. 1. 9. 3. 4. 8. 4. 5. 0. 7. 5.]

reshape:
 [[5. 9.]
 [1. 9.]
 [3. 4.]
 [8. 4.]
 [5. 0.]
 [7. 5.]]

transpose:
 [[5. 3. 5.]
 [9. 4. 0.]
 [1. 8. 7.]
 [9. 4. 5.]]
T shape: (4, 3)


In [47]:
import numpy as np

ohlc = np.array([
    [1.1000, 1.1100, 1.0950, 1.1050],
    [1.1050, 1.1200, 1.1000, 1.1150],
    [1.1150, 1.1300, 1.1100, 1.1250],
    [1.1250, 1.1400, 1.1200, 1.1350],
    [1.1350, 1.1500, 1.1300, 1.1450],
    [1.1450, 1.1550, 1.1400, 1.1500],
])

print("Original shape:", ohlc.shape)

ohlc_2weeks = ohlc.reshape((2, 3, 4))
print("Reshaped:", ohlc_2weeks.shape)

flat = ohlc.ravel()
print("Flat shape:", flat.shape)
print("Flat values:", flat)

Original shape: (6, 4)
Reshaped: (2, 3, 4)
Flat shape: (24,)
Flat values: [1.1   1.11  1.095 1.105 1.105 1.12  1.1   1.115 1.115 1.13  1.11  1.125
 1.125 1.14  1.12  1.135 1.135 1.15  1.13  1.145 1.145 1.155 1.14  1.15 ]


In [48]:
import numpy as np

rg = np.random.default_rng(1)

a = np.floor( 10 * rg.random((2, 2)))
b = np.floor( 10 * rg.random((2, 2)))

print("a:\n", a)
print("\nb:\n", b)

print("\nvstack (top to bottom):")
print(np.vstack((a,b)))
print("vstack shape:", np.vstack((a, b)).shape)

print("\nhstack (left to right):")
print(np.hstack((a, b)))
print("hstack shape:", np.hstack((a, b)).shape)


a:
 [[5. 9.]
 [1. 9.]]

b:
 [[3. 4.]
 [8. 4.]]

vstack (top to bottom):
[[5. 9.]
 [1. 9.]
 [3. 4.]
 [8. 4.]]
vstack shape: (4, 2)

hstack (left to right):
[[5. 9. 3. 4.]
 [1. 9. 8. 4.]]
hstack shape: (2, 4)


In [51]:
import numpy as np
from numpy import newaxis

rg = np.random.default_rng(1)
a_2d = np.floor(10 * rg.random((2, 2)))
b_2d = np.floor(10 * rg.random((2, 2)))

print("column_stack with 2D:")
print(np.column_stack((a_2d, b_2d)))

a = np.array([4., 2.])
b = np.array([3., 8.])

print("\ncolumn_stack with 1D:")
print(np.column_stack((a, b)))
print("shape:", np.column_stack((a, b)).shape)

print("\nhstack with 1D:")
print(np.hstack((a, b)))
print("shape:", np.hstack((a, b)).shape)

print("\ncolumn_stack with newaxis")
print(np.column_stack((a[:, newaxis], b[:, newaxis])))

print("\nhstack with newaxis:")
print(np.hstack((a[:, newaxis], b[:, newaxis])))

column_stack with 2D:
[[5. 9. 3. 4.]
 [1. 9. 8. 4.]]

column_stack with 1D:
[[4. 3.]
 [2. 8.]]
shape: (2, 2)

hstack with 1D:
[4. 2. 3. 8.]
shape: (4,)

column_stack with newaxis
[[4. 3.]
 [2. 8.]]

hstack with newaxis:
[[4. 3.]
 [2. 8.]]


In [53]:
import numpy as np

print("r_basic:", np.r_[1:4, 0, 4])

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("\nr_ like vstack:\n", np.r_[a, b])
print("\nc_ like hstack:\n", np.c_[a, b])

levels = np.r_[1.10:1.13:0.01, 1.20]
print("\nTrading levels:", levels)

r_basic: [1 2 3 0 4]

r_ like vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

c_ like hstack:
 [[1 2 5 6]
 [3 4 7 8]]

Trading levels: [1.1  1.11 1.12 1.2 ]


In [57]:
import numpy as np

rg = np.random.default_rng(1)
a = np.floor(10 * rg.random((2, 12)))
print("original:\n", a)
print("shape:", a.shape)

print("\nhsplit into 3:")
for i, part in enumerate(np.hsplit(a, 3)):
  print(f"part {i+1}:\n", part)

ohlcv = np.array([[1.10, 1.11, 1.09, 1.10, 1000],
                  [1.11, 1.12, 1.10, 1.11, 1500]])
ohlc, volume = np.hsplit(ohlcv, [4])
print("\nOHLC:\n", ohlc)
print("Volume:\n", volume)

original:
 [[5. 9. 1. 9. 3. 4. 8. 4. 5. 0. 7. 5.]
 [3. 7. 3. 4. 1. 4. 2. 2. 7. 2. 4. 9.]]
shape: (2, 12)

hsplit into 3:
part 1:
 [[5. 9. 1. 9.]
 [3. 7. 3. 4.]]
part 2:
 [[3. 4. 8. 4.]
 [1. 4. 2. 2.]]
part 3:
 [[5. 0. 7. 5.]
 [7. 2. 4. 9.]]

OHLC:
 [[1.1  1.11 1.09 1.1 ]
 [1.11 1.12 1.1  1.11]]
Volume:
 [[1000.]
 [1500.]]
